server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka  # Usa 127.0.0.1 en lugar de localhost
    fetch-registry: true  # Obtiene otros servicios de Eureka
    register-with-eureka: true  # Se registra en Eureka
  instance:
    prefer-ip-address: true  # Usa la IP en lugar del hostname
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
