server:
  port: 8081

spring:
  application:
    name: user-service  # Nombre del servicio para Eureka y Config Server
  cloud:
    config:
      uri: http://localhost:8888  # URL del Config Server
      fail-fast: true  # Si falla la configuraci칩n, la app no inicia
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_users?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Opci칩n para actualizar la base de datos autom치ticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Dialecto de MySQL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # URL del servidor Eureka
    register-with-eureka: true  # Registra este servicio en Eureka
    fetch-registry: true  # Obtiene informaci칩n de otros servicios registrados
  instance:
    prefer-ip-address: true  # Usa la IP en lugar del nombre de host para registrarse

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
